"""Build Caser context sections from current business read APIs."""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

from src.backend.application.agent.evidence_agent.service.orchestrator import (
    ReviewAdvisorService,
)
from src.backend.application.audit.review.build_materials_uc import (
    StatisticalMaterialUseCase,
)
from src.backend.application.audit.review.get_case_detail_uc import GetCaseDetailUseCase
from src.backend.domain.audit.review.entities import CaseDetail, MedicalRecordDocument
from src.backend.domain.caser_context.entities import (
    CASER_SECTION_KEYS,
    CASER_SECTION_SCHEMA_VERSION,
    CaserSectionMeta,
    validate_section_payload,
)


@dataclass(slots=True)
class BuiltCaserSection:
    """One validated section generated by the builder."""

    section_key: str
    status: str
    completeness: str
    payload: dict[str, Any]
    payload_hash: str
    source_refs: list[str]
    source_versions: dict[str, str]
    generated_by: str = "caser_context_builder"


class CaserSectionBuilder:
    """Build all Caser read-model sections for one case."""

    def __init__(
        self,
        *,
        get_case_detail: GetCaseDetailUseCase,
        statistical_materials: StatisticalMaterialUseCase,
        evidence_agent: ReviewAdvisorService | None,
    ) -> None:
        self._get_case_detail = get_case_detail
        self._statistical_materials = statistical_materials
        self._evidence_agent = evidence_agent

    @property
    def section_keys(self) -> list[str]:
        return list(CASER_SECTION_KEYS)

    def build(self, case_id: str, section_key: str) -> BuiltCaserSection:
        if section_key not in CASER_SECTION_KEYS:
            raise ValueError(f"Unknown Caser section: {section_key}")
        data = self._get_case_detail.execute(case_id)
        case = data.case
        materials = None
        if section_key in {
            "claimant_profile",
            "material_overview",
            "medical_materials",
            "prescription_materials",
            "settlement_materials",
        }:
            materials = self._statistical_materials.build_for_case(case)
        analysis = None
        if section_key in {"case_judgement", "verification_items"} and self._evidence_agent is not None:
            analysis = self._evidence_agent.get_current_analysis(case_id)

        payload = getattr(self, f"_build_{section_key}")(
            case,
            data.evidence,
            materials,
            analysis,
            data.notes or [],
        )
        status = str(payload["meta"]["status"])
        completeness = str(payload["meta"]["completeness"])
        validated = validate_section_payload(section_key, payload)
        payload_hash = _payload_hash(validated)
        return BuiltCaserSection(
            section_key=section_key,
            status=status,
            completeness=completeness,
            payload=validated,
            payload_hash=payload_hash,
            source_refs=list(dict.fromkeys(payload["meta"].get("source_refs", []))),
            source_versions=dict(payload["meta"].get("source_versions", {})),
        )

    def _meta(
        self,
        case: CaseDetail,
        section_key: str,
        *,
        status: str = "ready",
        completeness: str = "full",
        source_refs: list[str] | None = None,
        source_versions: dict[str, str] | None = None,
        notes: list[str] | None = None,
    ) -> dict[str, Any]:
        meta = CaserSectionMeta(
            schema_version=CASER_SECTION_SCHEMA_VERSION,
            case_id=case.case_id,
            section_key=section_key,
            status=status,  # type: ignore[arg-type]
            completeness=completeness,  # type: ignore[arg-type]
            source_refs=list(dict.fromkeys(source_refs or [])),
            source_versions=source_versions or _case_source_versions(case),
            generated_at=datetime.now(timezone.utc),
            notes=notes or [],
        )
        return meta.model_dump(mode="json")

    def _build_case_basic_info(
        self,
        case: CaseDetail,
        _evidence: Any,
        _materials: Any,
        _analysis: Any,
        _notes: list[Any],
    ) -> dict[str, Any]:
        return {
            "meta": self._meta(
                case,
                "case_basic_info",
                source_refs=[f"case:{case.case_id}:basic"],
            ),
            "case_number": case.case_id,
            "case_type": case.case_type,
            "review_status": case.review_status,
            "claimant_ref": case.subject_ref,
            "access_method": _access_method(case),
            "case_title": case.case_title,
            "claim_summary": case.claim_summary,
            "claim_amount": case.claim_amount,
            "insured_region": _case_context_value(case, "insured_region"),
            "treatment_region": _case_context_value(case, "treatment_region"),
            "visit_type": _case_context_value(case, "visit_type"),
            "claim_mode": _case_context_value(case, "claim_mode"),
            "direct_settlement": _case_context_value(case, "direct_settlement"),
            "filing_status": _case_context_value(case, "filing_status"),
            "emergency_material_status": _case_context_value(case, "emergency_material_status"),
            "diagnosis": _case_context_value(case, "diagnosis"),
            "case_context": case.case_context,
        }

    def _build_claimant_profile(
        self,
        case: CaseDetail,
        _evidence: Any,
        materials: Any,
        _analysis: Any,
        _notes: list[Any],
    ) -> dict[str, Any]:
        profile = getattr(materials, "subject_profile", None)
        return {
            "meta": self._meta(
                case,
                "claimant_profile",
                completeness="full" if profile is not None else "partial",
                source_refs=[f"case:{case.case_id}:claimant_profile"],
            ),
            "claimant_code": getattr(profile, "subject_ref", None) or case.subject_ref,
            "gender": getattr(profile, "gender", "unknown"),
            "age_group": getattr(profile, "age_group", "unknown"),
            "insurance_type": getattr(profile, "insurance_type", "unknown"),
            "chronic_condition_tags": list(getattr(profile, "chronic_condition_tags", []) or []),
            "allergy_history": getattr(profile, "allergy_history", "unknown"),
            "patient_group_tags": list(getattr(profile, "patient_group_tags", []) or []),
        }

    def _build_material_overview(
        self,
        case: CaseDetail,
        _evidence: Any,
        materials: Any,
        _analysis: Any,
        _notes: list[Any],
    ) -> dict[str, Any]:
        documents = list(getattr(materials, "documents", []) or [])
        return {
            "meta": self._meta(
                case,
                "material_overview",
                completeness="full" if documents else "partial",
                source_refs=[f"material:{doc.document_id}" for doc in documents],
                source_versions={"material_template": getattr(materials, "template_version", "")},
            ),
            "material_total": len(documents),
            "groups": [
                {
                    "category_id": category.category_id,
                    "title": category.title,
                    "count": len(category.documents),
                    "materials": [_material_overview_item(doc) for doc in category.documents],
                }
                for category in getattr(materials, "categories", []) or []
            ],
        }

    def _build_medical_materials(self, case: CaseDetail, _evidence: Any, materials: Any, _analysis: Any, _notes: list[Any]) -> dict[str, Any]:
        docs = _docs_by_category(materials, "clinical")
        return {
            "meta": self._meta(
                case,
                "medical_materials",
                completeness="full" if docs else "partial",
                source_refs=[f"material:{doc.document_id}" for doc in docs],
                source_versions={"material_template": getattr(materials, "template_version", "")},
            ),
            "materials": [_medical_material(doc) for doc in docs],
        }

    def _build_prescription_materials(self, case: CaseDetail, _evidence: Any, materials: Any, _analysis: Any, _notes: list[Any]) -> dict[str, Any]:
        docs = _docs_by_category(materials, "prescription")
        return {
            "meta": self._meta(
                case,
                "prescription_materials",
                completeness="full" if docs else "partial",
                source_refs=[f"material:{doc.document_id}" for doc in docs],
                source_versions={"material_template": getattr(materials, "template_version", "")},
            ),
            "materials": [_prescription_material(doc) for doc in docs],
        }

    def _build_settlement_materials(self, case: CaseDetail, _evidence: Any, materials: Any, _analysis: Any, _notes: list[Any]) -> dict[str, Any]:
        docs = _docs_by_category(materials, "settlement")
        return {
            "meta": self._meta(
                case,
                "settlement_materials",
                completeness="full" if docs else "partial",
                source_refs=[f"material:{doc.document_id}" for doc in docs],
                source_versions={"material_template": getattr(materials, "template_version", "")},
            ),
            "materials": [_settlement_material(doc) for doc in docs],
            "settlement_summary": _settlement_summary(case),
            "non_drug_fee_items": _non_drug_fee_items(docs),
        }

    def _build_statistics_report(self, case: CaseDetail, _evidence: Any, _materials: Any, _analysis: Any, _notes: list[Any]) -> dict[str, Any]:
        metrics = _statistics_metrics(case)
        return {
            "meta": self._meta(
                case,
                "statistics_report",
                completeness="partial",
                source_refs=[f"case:{case.case_id}:statistics"],
                notes=["Peer baseline values are not available in v1."],
            ),
            "metric_count": len(metrics),
            "metric_baseline_status": "not_available",
            "groups": _group_statistics(metrics),
        }

    def _build_risk_score(self, case: CaseDetail, _evidence: Any, _materials: Any, _analysis: Any, _notes: list[Any]) -> dict[str, Any]:
        breakdown = case.risk_score_breakdown.model_dump(mode="json") if case.risk_score_breakdown else {}
        components = list(breakdown.get("components", []) or [])
        component_by_key = {str(item.get("key")): item for item in components if isinstance(item, dict)}
        model_signal = {
            "result": case.fraud_screening.result,
            "label": case.fraud_screening.label,
            "source": case.fraud_screening.source,
            "reason": case.fraud_screening.reason,
            "probability": case.fraud_screening.probability,
            "source_ref": f"risk:{case.case_id}:model_warning",
        }
        return {
            "meta": self._meta(
                case,
                "risk_score",
                source_refs=[f"risk:{case.case_id}:model_warning"],
            ),
            "overall_strength": breakdown.get("display_score") or f"{case.risk_score:.2f}",
            "risk_level": case.risk_level,
            "model_warning": {
                **(component_by_key.get("model_warning") or {}),
                "signal": model_signal,
            },
            "rule_check": component_by_key.get("rule_check") or {},
            "peer_deviation": component_by_key.get("peer_deviation") or {},
            "data_flow": component_by_key.get("data_flow") or {},
            "components": components,
        }

    def _build_evidence_package(self, case: CaseDetail, evidence: Any, _materials: Any, _analysis: Any, _notes: list[Any]) -> dict[str, Any]:
        ev = evidence.model_dump(mode="json") if hasattr(evidence, "model_dump") else {}
        clues = []
        for card in ev.get("rule_cards", []) or []:
            clues.append(
                {
                    "name": card.get("rule_name"),
                    "status": "hit",
                    "source": card.get("source_ref"),
                }
            )
        return {
            "meta": self._meta(
                case,
                "evidence_package",
                source_refs=[item.get("ref", "") for item in ev.get("citations", []) or []],
            ),
            "base_summary": {
                "risk_summary": ev.get("risk_summary"),
                "model_warning": ev.get("model_evidence"),
                "rule_hit_count": len(ev.get("rule_cards", []) or []),
                "material_prompt": "; ".join(ev.get("missing_information", []) or []),
            },
            "discovered_clues": clues,
            "source_basis": {
                "model_warning": {"source": f"risk:{case.case_id}:model_warning", "description": case.model_signal_source},
                "rule_results": {"source": case.rule_pool_version, "description": "rule hit results"},
                "safe_field_summary": {"source": f"case:{case.case_id}:source_record", "description": "sanitized feature record"},
                "statistics_material_summary": {"source": f"case:{case.case_id}:statistics", "description": "statistics view"},
            },
        }

    def _build_case_judgement(self, case: CaseDetail, _evidence: Any, _materials: Any, analysis: Any, _notes: list[Any]) -> dict[str, Any]:
        if analysis is None:
            return {
                "meta": self._meta(
                    case,
                    "case_judgement",
                    status="not_ready",
                    completeness="not_available",
                    source_refs=[],
                    notes=["Review Advisor current analysis is not available."],
                ),
                "system_risk_prompt": {},
                "evidence_review_result": {},
                "review_note": "",
                "clue_review": {},
            }
        payload = analysis.model_dump(mode="json")
        grouped = {"supported": [], "needs_review": [], "unconfirmed": []}
        for item in payload.get("clue_reviews", []) or []:
            if isinstance(item, dict):
                grouped.setdefault(str(item.get("status") or "unconfirmed"), []).append(item)
        return {
            "meta": self._meta(
                case,
                "case_judgement",
                source_refs=[f"analysis:{analysis.run_id}"],
                source_versions={"review_advisor_prompt": analysis.prompt_version},
            ),
            "system_risk_prompt": payload.get("system_risk_prompt") or {},
            "evidence_review_result": payload.get("evidence_review") or {},
            "review_note": payload.get("risk_overview") or "",
            "clue_review": grouped,
        }

    def _build_verification_items(self, case: CaseDetail, _evidence: Any, _materials: Any, analysis: Any, _notes: list[Any]) -> dict[str, Any]:
        if analysis is None:
            return {
                "meta": self._meta(
                    case,
                    "verification_items",
                    status="not_ready",
                    completeness="not_available",
                    source_refs=[],
                    notes=["Review Advisor current analysis is not available."],
                ),
                "risk_related_tasks": [],
                "global_scan_tasks": [],
            }
        payload = analysis.model_dump(mode="json")
        tasks = []
        for index, item in enumerate(payload.get("verification_checklist", []) or [], start=1):
            if isinstance(item, dict):
                tasks.append(_verification_task(index, item))
            else:
                tasks.append(
                    {
                        "task_id": f"verify-{index:03d}",
                        "task_name": str(item),
                        "task_status": "pending",
                        "action": "manual_check",
                        "reason": "",
                        "source_refs": [],
                    }
                )
        return {
            "meta": self._meta(
                case,
                "verification_items",
                source_refs=[f"analysis:{analysis.run_id}"],
                source_versions={"review_advisor_prompt": analysis.prompt_version},
            ),
            "risk_related_tasks": tasks,
            "global_scan_tasks": [],
        }

    def _build_rule_verification(self, case: CaseDetail, _evidence: Any, _materials: Any, _analysis: Any, _notes: list[Any]) -> dict[str, Any]:
        rules = [_rule_verification_item(rule) for rule in case.rule_hits]
        return {
            "meta": self._meta(
                case,
                "rule_verification",
                source_refs=[rule.evidence_ref for rule in case.rule_hits],
            ),
            "summary": {
                "total": len(case.rule_hits),
                "hit_count": len([rule for rule in case.rule_hits if rule.hit]),
                "rule_pool_version": case.rule_pool_version,
                "rule_baseline_version": case.rule_baseline_version,
            },
            "rules": rules,
        }


def _payload_hash(payload: dict[str, Any]) -> str:
    raw = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _case_source_versions(case: CaseDetail) -> dict[str, str]:
    return {
        "rule_pool": case.rule_pool_version,
        "rule_baseline": case.rule_baseline_version,
    }


def _access_method(case: CaseDetail) -> str:
    source = str(case.source_record.get("source_system") or "")
    if source:
        return source
    if case.source_record:
        return "upstream_wide_record"
    return "legacy_feature_record"


def _case_context_value(case: CaseDetail, key: str) -> Any:
    context = case.case_context or {}
    if not isinstance(context, dict):
        return None if key == "direct_settlement" else ""
    value = context.get(key)
    if value in (None, ""):
        return None if key == "direct_settlement" else ""
    return value


def _docs_by_category(materials: Any, category_id: str) -> list[MedicalRecordDocument]:
    if materials is None:
        return []
    return [doc for doc in getattr(materials, "documents", []) or [] if doc.category_id == category_id]


def _material_overview_item(doc: MedicalRecordDocument) -> dict[str, Any]:
    return {
        "material_id": doc.document_id,
        "name": doc.title,
        "occurred_at": doc.occurred_at or doc.visit_date,
        "source": doc.material_source,
        "shape": doc.material_shape,
        "status": doc.status,
        "operation": "read_only",
        "source_ref": f"material:{doc.document_id}",
    }


def _material_basic(doc: MedicalRecordDocument) -> dict[str, Any]:
    return {
        "material_type": doc.document_type,
        "occurred_at": doc.occurred_at or doc.visit_date,
        "material_source": doc.material_source,
        "material_shape": doc.material_shape,
        "material_status": doc.status,
        "source_ref": f"material:{doc.document_id}",
    }


def _medical_material(doc: MedicalRecordDocument) -> dict[str, Any]:
    return {
        "material_id": doc.document_id,
        "name": doc.title,
        "basic_info": _material_basic(doc),
        "content": {
            "chief_complaint": _metadata(doc, "chief_complaint"),
            "diagnosis": _metadata(doc, "diagnosis"),
            "diagnosis_code": _metadata(doc, "diagnosis_code"),
            "claimant_features": _metadata(doc, "claimant_features"),
            "raw_material_summary": "; ".join(doc.summary_items) or doc.content[:800],
        },
        "visit_details": [_table_row(row) for table in doc.tables for row in table.rows[:20]][:50],
        "check_points": doc.check_points,
    }


def _prescription_material(doc: MedicalRecordDocument) -> dict[str, Any]:
    details = [_table_row(row) for table in doc.tables for row in table.rows[:50]][:100]
    return {
        "material_id": doc.document_id,
        "name": doc.title,
        "basic_info": _material_basic(doc),
        "content": {
            "raw_material_summary": "; ".join(doc.summary_items) or doc.content[:800],
        },
        "prescription_drug_details": details,
        "image_assets": [
            {
                "asset_id": asset.asset_id,
                "title": asset.title,
                "asset_type": asset.asset_type,
                "file_type": asset.file_type,
                "preview_url": asset.preview_url,
            }
            for asset in doc.assets
        ],
        "check_points": doc.check_points,
    }


def _settlement_material(doc: MedicalRecordDocument) -> dict[str, Any]:
    return {
        "material_id": doc.document_id,
        "name": doc.title,
        "basic_info": _material_basic(doc),
        "content": {"raw_material_summary": "; ".join(doc.summary_items) or doc.content[:800]},
        "tables": [table.model_dump(mode="json") for table in doc.tables[:5]],
        "check_points": doc.check_points,
    }


def _metadata(doc: MedicalRecordDocument, key: str) -> Any:
    return dict(doc.metadata or {}).get(key, "")


def _table_row(row: dict[str, Any]) -> dict[str, Any]:
    return {str(key): value for key, value in row.items()}


def _settlement_summary(case: CaseDetail) -> dict[str, Any]:
    source = case.source_record or {}
    return {
        "claim_total_fee": _first_present(source, ["ALL_SUM", "claim_total_fee"]),
        "approved_amount": _first_present(source, ["本次审批金额", "approved_amount"]),
        "fund_payment_amount": _first_present(source, ["统筹支付金额", "fund_payment_amount"]),
        "personal_account_amount": _first_present(source, ["个人账户金额", "personal_account_amount"]),
        "drug_fee": _field_contains(source, ["药品", "药费"]),
        "exam_fee": _field_contains(source, ["检查"]),
        "treatment_fee": _field_contains(source, ["治疗"]),
        "medical_material_fee": _field_contains(source, ["材料"]),
    }


def _non_drug_fee_items(docs: list[MedicalRecordDocument]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for doc in docs:
        for table in doc.tables:
            for row in table.rows[:80]:
                item = _table_row(row)
                text = json.dumps(item, ensure_ascii=False)
                if "药" not in text and "drug" not in text.lower():
                    rows.append(item)
    return rows[:120]


def _statistics_metrics(case: CaseDetail) -> list[dict[str, Any]]:
    source = {**(case.source_record or {}), **(case.input_features or {})}
    metrics = []
    for key, value in source.items():
        if str(key).upper() == "RES":
            continue
        metrics.append(
            {
                "feature_name": str(key),
                "current_value": value,
                "peer_median": None,
                "p75": None,
                "p90": None,
                "baseline_status": "not_available",
                "hint": _metric_hint(str(key), value),
            }
        )
    return metrics


def _group_statistics(metrics: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    groups = {
        "visit_statistics": [],
        "visit_day_statistics": [],
        "institution_statistics": [],
        "fee_statistics": [],
        "payment_statistics": [],
        "drug_statistics": [],
        "fee_structure_statistics": [],
        "process_status_statistics": [],
        "other_statistics": [],
    }
    for metric in metrics:
        key = str(metric["feature_name"])
        target = "other_statistics"
        if any(token in key for token in ("就诊", "visit")):
            target = "visit_day_statistics" if "天" in key else "visit_statistics"
        elif any(token in key for token in ("医院", "机构", "institution")):
            target = "institution_statistics"
        elif any(token in key for token in ("支付", "基金", "account", "pay")):
            target = "payment_statistics"
        elif any(token in key for token in ("药", "drug")):
            target = "drug_statistics"
        elif any(token in key for token in ("费用", "金额", "SUM", "fee", "amount")):
            target = "fee_statistics"
        elif any(token in key for token in ("占比", "比例", "ratio")):
            target = "fee_structure_statistics"
        elif any(token in key for token in ("状态", "流程", "status")):
            target = "process_status_statistics"
        groups[target].append(metric)
    return groups


def _metric_hint(_key: str, _value: Any) -> str:
    return "Baseline comparison is not available in v1."


def _rule_verification_item(rule: Any) -> dict[str, Any]:
    return {
        "rule_id": rule.rule_id,
        "rule_name": rule.rule_name,
        "rule_status": "hit" if rule.hit else "not_hit",
        "attention_level": rule.severity,
        "verification_description": rule.reason,
        "verification_result": {
            "current_value": rule.current_value,
            "threshold": rule.threshold,
            "action": rule.action,
            "layer": rule.layer,
        },
        "basis": [
            {
                "basis_type": "base",
                "source_ref": rule.evidence_ref,
                "description": rule.business_explanation or rule.reason,
            },
            {
                "basis_type": "current",
                "source_ref": rule.evidence_ref,
                "description": f"current={rule.current_value}; threshold={rule.threshold}",
            },
            {
                "basis_type": "standard",
                "source_ref": rule.version,
                "description": rule.version,
            },
        ],
        "check_items": [item.model_dump(mode="json") for item in rule.check_items],
    }


def _verification_task(index: int, item: dict[str, Any]) -> dict[str, Any]:
    return {
        "task_id": str(item.get("task_id") or f"verify-{index:03d}"),
        "task_name": str(item.get("title") or item.get("statement") or item.get("name") or "verification task"),
        "task_status": str(item.get("status") or "pending"),
        "action": str(item.get("action") or "manual_check"),
        "reason": str(item.get("reason") or item.get("rationale") or ""),
        "source_refs": [str(ref) for ref in item.get("source_refs", []) if ref],
    }


def _first_present(source: dict[str, Any], keys: list[str]) -> Any:
    for key in keys:
        if key in source:
            return source[key]
    return None


def _field_contains(source: dict[str, Any], markers: list[str]) -> Any:
    for key, value in source.items():
        if any(marker in str(key) for marker in markers):
            return value
    return None
