"""Information-need-native contracts for Policy Expert answers."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from src.backend.application.agent.expert_agent.service.policy_answer_contracts import (
    AnswerMode,
    ClaimCitation,
    NormalizedPolicyEvidence,
)


NeedStatus = Literal["pending", "supported", "partial", "missing", "conflicted"]
SupportRole = Literal["direct_answer", "supporting", "irrelevant", "conflict"]


class InformationNeedRequirement(BaseModel):
    """One user-visible information point that must be answered independently."""

    model_config = ConfigDict(extra="forbid")

    need_id: str = Field(min_length=1, max_length=80)
    need_text: str = Field(min_length=1, max_length=240)
    question_span: str = Field(default="", max_length=300)
    answer_mode: AnswerMode = "process_rule"
    required: bool = True
    filters: dict[str, Any] = Field(default_factory=dict)
    status: NeedStatus = "pending"


class NeedEvidenceMatch(BaseModel):
    """Evidence support relationship for one information point."""

    model_config = ConfigDict(extra="forbid")

    match_id: str = Field(min_length=1, max_length=80)
    need_id: str = Field(min_length=1, max_length=80)
    evidence_id: str = Field(min_length=1, max_length=220)
    coverage_status: Literal["covered", "partial", "missing", "conflict"]
    support_role: SupportRole
    matched_spans: list[str] = Field(default_factory=list, max_length=6)
    score: float = Field(default=0.0, ge=0.0, le=1.0)
    reason: str = Field(default="", max_length=240)


class NeedFact(BaseModel):
    """One user-safe fact linked directly to an information point."""

    model_config = ConfigDict(extra="forbid")

    fact_id: str = Field(min_length=1, max_length=80)
    need_id: str = Field(min_length=1, max_length=80)
    fact_type: str = Field(min_length=1, max_length=120)
    value: dict[str, Any] = Field(default_factory=dict)
    user_facing_text: str = Field(min_length=1, max_length=600)
    evidence_refs: list[str] = Field(min_length=1, max_length=8)
    source_refs: list[str] = Field(min_length=1, max_length=8)
    evidence_quote: str = Field(min_length=1, max_length=1000)
    support_role: SupportRole = "direct_answer"
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)


class NeedAnswer(BaseModel):
    """One concise answer corresponding to exactly one information point."""

    model_config = ConfigDict(extra="forbid")

    need_id: str = Field(min_length=1, max_length=80)
    need_text: str = Field(min_length=1, max_length=240)
    status: NeedStatus
    answer_text: str = Field(min_length=1, max_length=900)
    fact_refs: list[str] = Field(default_factory=list, max_length=12)
    source_refs: list[str] = Field(default_factory=list, max_length=8)
    citation_ids: list[str] = Field(default_factory=list, max_length=8)
    missing_reason: str = Field(default="", max_length=300)


class NeedClaim(BaseModel):
    """Claim contract exposed to Case Agent without legacy slot fields."""

    model_config = ConfigDict(extra="forbid")

    claim_id: str = Field(min_length=1, max_length=80)
    need_id: str = Field(min_length=1, max_length=80)
    need_text: str = Field(min_length=1, max_length=240)
    text: str = Field(min_length=1, max_length=900)
    fact_refs: list[str] = Field(default_factory=list, max_length=12)
    source_refs: list[str] = Field(default_factory=list, max_length=8)
    citation_ids: list[str] = Field(default_factory=list, max_length=8)
    support_status: Literal["supported", "partial", "unsupported", "conflicted"]


class NeedFirstPolicyAnswer(BaseModel):
    """Complete answer payload generated by the information-need-native pipeline."""

    model_config = ConfigDict(extra="forbid")

    pipeline_version: str = "information_need_v2"
    answer_mode: AnswerMode = "process_rule"
    information_needs: list[str] = Field(default_factory=list, max_length=12)
    expert_answer: str = Field(default="", max_length=2000)
    answer_markdown: str = Field(default="", max_length=4000)
    answer_requirements: list[InformationNeedRequirement] = Field(default_factory=list, max_length=16)
    evidence_matches: list[NeedEvidenceMatch] = Field(default_factory=list, max_length=80)
    extracted_facts: list[NeedFact] = Field(default_factory=list, max_length=60)
    need_answers: list[NeedAnswer] = Field(default_factory=list, max_length=16)
    claims: list[NeedClaim] = Field(default_factory=list, max_length=30)
    claim_plan: list[dict[str, Any]] = Field(default_factory=list, max_length=30)
    citations: list[ClaimCitation] = Field(default_factory=list, max_length=30)
    source_refs: list[str] = Field(default_factory=list, max_length=20)
    support_status: Literal["supported", "partial", "unsupported", "conflicted"] = "unsupported"


__all__ = [
    "ClaimCitation",
    "InformationNeedRequirement",
    "NeedAnswer",
    "NeedClaim",
    "NeedEvidenceMatch",
    "NeedFact",
    "NeedFirstPolicyAnswer",
    "NormalizedPolicyEvidence",
]
